function Hd = cheb_highpass
%CHEB_HIGHPASS Returns a discrete-time filter object.
% M-File generated by MATLAB(R) 7.7 and the Signal Processing Toolbox 6.10.
% Chebyshev Type I Highpass filter designed using FDESIGN.HIGHPASS.
% All frequency values are in Hz.

if nargin == 0
   Fs = evalin( 'base', 'mean_samp_rate' );  % Sampling Frequency
end
     
N      = 8;                                  % Order
Fpass  = 0.1;                                % Passband Frequency
Apass  = 1.0;                                % Passband Ripple (dB)
%Fpas1 = 0.1
%Fpas2 = 1.0

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.highpass('N,Fp,Ap', N, Fpass, Apass, Fs);
Hd = design(h, 'cheby1');